site_name: "Git Hooks (JEM234)"
repo_url: https://github.com/luk27official/JEM234/

nav:
    - "Introduction": "index.md"
    - "Git Hooks": "git_hooks.md"

# pip install mkdocs-material
theme:
    name: material
